### ISSUE TITLE
Use Cases for replify?

### ISSUE THREAD

**Issue by sathishsoundharajan** [dshaw/replify#15]
Could you please brief use cases for this module?

I tried it with some examples, but I think I am not leverage-ing this module properly.

**Comment by dshaw** [comment]
@bboysathish Great feedback. Looking at the examples and the Readme, I agree that there is a lot of implied knowledge.

**Comment by sathishsoundharajan** [comment]
Hi @dshaw this is an outstanding issue. I am closing this now. If you are going to write use_case.md / examples.md . IMO that would be great. Thanks :+1:

**Comment by dshaw** [comment]
Thanks, @bboysathish. Good feedback. Contributions welcome.
