### ISSUE TITLE
Telnet - tab completion

### ISSUE THREAD

**Issue by ghost** [dshaw/replify#2]
Is it possible to get tab completion when connecting with telnet, or is there another way of connecting where we can get tab completion?

Chris

**Comment by dshaw** [comment]
Telnet just doesn't have the functionality to be able to handle this.

You can use SOCAT to get history, but if you want full tab completion use: [repl-client (rc)](https://github.com/dshaw/repl-client). We use this at Voxer and love it.

You might want to check out my RealtimeConf talk for more on this: https://github.com/dshaw/2012-10-realtimeconf , specifically http://dshaw.github.com/2012-10-realtimeconf/#/8 .

**Comment by ghost** [comment]
Wow, such a detailed response - thanks!
