### ISSUE TITLE
Need a way to stop replify

### ISSUE THREAD

**Issue by thlorenz** [dshaw/replify#8]
Lets say my server is running smoothly and I repled into it, i.e. by turning replify on via some secret `/replify/on` route. I did the necessary inspections and now want to turn replify off again i.e. via secret `/replify/off` route.

Wondering what's the easiest way to get that implemented and if others agree that this is a useful feature., 

My idea is to move `var replServer` up into the `module.exports function` scope, so that we can return `{ stop: function () { server.stop(); } }`.

**Comment by dshaw** [comment]
Why not just `return replServer`? (Yes, you'd still have to move `replServer` into scope.)

I'm down for this, especially since this wouldn't change existing behavior.

**Comment by thlorenz** [comment]
`return replServer` is fine as well as it gives you even more power. I'll take a crack at this when I have some breathing room ;)

**Comment by dshaw** [comment]
Started moving toward enabling this functionality. `replServer.close()` is fine. However with this, there's no good way to restart it again.

**Comment by thlorenz** [comment]
I guess totally killing it and starting up an entire new repl server when I restart would be sufficient. That should be possible right?

**Comment by dshaw** [comment]
Totally. I'd like to have you experiment with the use case before adding additional API, which is totally doable.

Eventually, `start` and `stop` could be something like this:

``` js
replServer.start = function () {
  fs.mkdir(options.path, function (err) {
    if (err && err.code !== 'EEXIST') {
      return logger.error('error making repl directory: ' + replDir, err)
    }

    fs.unlink(options.replPath, function () {
      // NOTE: Intentionally not listening for any errors.

      replServer.listen(options.replPath)
    })
  })
}

replServer.stop = replServer.close

if (options.autostart) {
  replServer.start()
}
```

I'm going to publish this as it stands for now, but leave this open for further discussion.

**Comment by dshaw** [comment]
I'm going to close this for now. Please feel free to reopen if you explore this deeper and have a PR.
