### ISSUE TITLE
EACCESS when running on Windows

### ISSUE THREAD

**Issue by mateodelnorte** [dshaw/replify#9]
I'm getting a `repl server error { [Error: listen EACCES] code: 'EACCES', errno: 'EACCES', syscall: 'listen' }` error when running replify on Windows. The error does not occur when running on Ubuntu.

**Comment by dshaw** [comment]
Looking into it. Possibly related: https://github.com/joyent/node/issues/2797

@mateodelnorte Could you try this?

``` js
var replify = require('replify')
replify({ name: 'repl-windows', path: __dirname })
```

**Comment by mateodelnorte** [comment]
Yup. Samesies. 

```
$ cat test.js                                                                                                 
var replify = require('replify');                                                                             
replify({ name: 'repl-windows', path: __dirname });

$ node test.js                                                                                                
repl server error { [Error: listen EACCES] code: 'EACCES', errno: 'EACCES', syscall: 'listen' }               
```

**Comment by mateodelnorte** [comment]
Btw, the default setting of /tmp/repl throws a different error on Windows as well - caused by the fact that the /tmp/repl directory doesn't exist. Not a problem, if you can override and provide a dir, of course.

```
C:\Users\mwalters\development\email-service\node_modules\replify\replify.js:95          
      return logger.error('error making repl directory: ' + replDir, err)               
                                                            ^                           
ReferenceError: replDir is not defined                                                  
    at C:\Users\mwalters\development\email-service\node_modules\replify\replify.js:95:61
    at Object.oncomplete (fs.js:107:15)                                                 
```

I've tested with both msysgit bash emulation as well as regular Windows, under powershell. Same results for both.

**Comment by dshaw** [comment]
@mateodelnorte Thanks for checking. I'll ask around about the state of domain socket support on Windows.

**Comment by mateodelnorte** [comment]
Thanks. Big fan of this module, btw. Thanks a bunch.

**Comment by dshaw** [comment]
@mateodelnorte Would you mind creating an issue for the Windows default directory too? IFF we can use it on Windows, we should definitely provide a sensible default.

**Comment by dshaw** [comment]
@mateodelnorte #12 and [v1.2.0](https://github.com/dshaw/replify/tree/v1.2.0) should fix this. Would you mind updating and checking.
